[Link] StripePaymentSheet depends on StripeLinkCore
stripe/stripe-ios pull request #2351
Opened 2023-03-03 21:31 UTC by bmelts-stripe

## Summary
Added StripeLinkCore as a dependency of StripePaymentSheet, and updated documentation. cc @kgaidis-stripe 

## Motivation
Part of the ongoing module creation process (see: https://github.com/stripe/stripe-ios/pull/2320, https://github.com/stripe/stripe-ios/pull/2335).

## Testing
Ran through wiki instructions, everything works as expected.

## Notes
I copied the wording in the documentation updates from the wiki, but I'm open to discussion on if there are better ways we should communicate this. I've also left the version undefined for `MIGRATING.md` - we should decide on what kind of bump we want to do for this (major or minor).

2023-03-03 22:36 UTC, kgaidis-stripe commented
@bmelts-stripe 

Does the merging of this PR mean that people will have to perform migration steps IF they use `StripePaymentSheet`?

Since this is a little bit of a migration commitment, I wonder what you think about trying to do this once for _any_ framework that will eventually depend on `StripeLinkCore`? Is it just `StripePaymentSheet` and then eventually `FinancialConnections`? For example, I wonder if Financial Connections should do this _now_ (even if we don't use it at the moment) because we will have to anyway. CC: @vardges-stripe

2023-03-16 22:53 UTC, eurias-stripe approved these changes

2023-03-16 22:53 UTC, eurias-stripe commented on CHANGELOG.md
> +## 24.0.0 yyyy-mm-dd
leave this as `x.x.x yyyy-mm-dd` the release script will replace it with the right version/date

2023-03-17 16:55 UTC, davidme-stripe requested changes
We're holding off on a major version bump for now.

2025-05-20 17:31 UTC, closed without merging