added option to select pln currency
stripe/stripe-ios pull request #2705
Opened 2023-07-04 15:45 UTC by fionnbarrett-stripe

## Summary

added option pln to payment sheet example
## Motivation

adding support for blik payment method which only supports pln
## Testing

## Changelog

2023-07-05 12:16 UTC, egor-stripe requested changes
AFAI the backend example app that PaymentSheet playground connects to doesn't yet support `PLN` currency. Can you please double check if this works without the backend change?

2023-07-06 11:51 UTC, fionnbarrett-stripe commented
the backend example app now supports `PLN` currency. payment methods using PLN appear to be fully working now in the example app.

2023-07-06 11:51 UTC, fionnbarrett-stripe reviewed
the backend example app now supports `PLN` currency. payment methods using PLN appear to be fully working now in the example app.

2023-07-06 11:59 UTC, egor-stripe approved these changes

2023-07-10 15:06 UTC, porter-stripe approved these changes

2023-07-11 09:39 UTC, merged